### ISSUE TITLE
Something U have to do when U use the third-party plug-in 'hexo-toc' together.

### ISSUE THREAD

**Issue by KevinHu-1024** [celsomiranda/hexo-renderer-markdown-it#35]
I had replaced the default md render by [hexo-renderer-markdown-it](https://github.com/celsomiranda/hexo-renderer-markdown-it). And I installed [hexo-toc](https://github.com/bubkoo/hexo-toc).

Then I noticed the rended page had something what didn't hiden:  and .

This issue need to configure *hexo-renderer-markdown-it*  by set `html: ture`

eg.(hexo's _config.yml)

```
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
```
